//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteGugu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cooperativa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cooperativa()
        {
            this.PedidoEstoque = new HashSet<PedidoEstoque>();
            this.ProdutorCooperativa = new HashSet<ProdutorCooperativa>();
            this.ValorUnitario = new HashSet<ValorUnitario>();
        }
    
        public int idcooperativa { get; set; }
        public string nomecoop { get; set; }
        public long telefone { get; set; }
        public string email { get; set; }
        public long cnpjcoop { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string regiao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoEstoque> PedidoEstoque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutorCooperativa> ProdutorCooperativa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValorUnitario> ValorUnitario { get; set; }
    }
}
