//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteGugu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaJuridica
    {
        public int idpessoa { get; set; }
        public long cnpj { get; set; }
        public string nomefant { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
