//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteGugu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaFisica
    {
        public int idpessoa { get; set; }
        public long cpf { get; set; }
        public string sexo { get; set; }
        public System.DateTime datanasc { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Produtor Produtor { get; set; }
    }
}
