//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteGugu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutorCooperativa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProdutorCooperativa()
        {
            this.Entrada = new HashSet<Entrada>();
        }
    
        public int idpessoa { get; set; }
        public int idcooperativa { get; set; }
    
        public virtual Cooperativa Cooperativa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrada> Entrada { get; set; }
        public virtual Produtor Produtor { get; set; }
    }
}
